name: Check Python code format

on: [push]

jobs:
  linter_name:
    name: runner / isort & black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check files using the isort import sorter
        uses: isort/isort-action@v1
        with:
          configuration: "--profile black --check-only"
          requirements-files: "requirements.txt"
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"